### ISSUE TITLE
README etc.

### ISSUE THREAD

**Issue by ForbesLindesay** [jstransformers/jstransformer-handlebars#1]
The readme needs updating to refer to handlebars rather than marked.  We should then update it to expose the same api as https://github.com/jstransformers/jstransformer-underscore

**Comment by hemanth** [comment]
Yikes! ;) 

Okies, will update as per underscore.

**Comment by hemanth** [comment]
@ForbesLindesay Something like below, makes sense?

``` js
exports.compile = function (str, options) {
  return function (locals) {
    return Handlebars.compile(str);
  };
};

exports.render = function (str, options, locals) {
  var compiled = exports.compile(str, options);
  if (typeof compiled === 'function') {
    return compiled(locals || options);
  }
};
```

**Comment by hemanth** [comment]
@TimothyGu ^

**Comment by TimothyGu** [comment]
@hemanth said:

> ``` js
> exports.compile = function (str, options) {
>   return function (locals) {
>     return Handlebars.compile(str);
>   };
> };
> ```

Why the redirection?

`Handlebars.compile(str)` already provides a perfectly fine `function (locals)`.

This should be good:

``` js
exports.compile = function (str, options) {
  for (var partial in options.partials) {
    Handlebars.registerPartial(partial, options.partials[partial]);
  }
  for (var helper in options.helpers) {
    Handlebars.registerHelper(helper, options.helpers[helper]);
  }
  return Handlebars.compile(str, options);
}
```

as `Handlebars.compile` has the same signature as jstransformer's API (`function (str, options)`).

> ``` js
> exports.render = function (str, options, locals) {
>   var compiled = exports.compile(str, options);
>   if (typeof compiled === 'function') {
>     return compiled(locals || options);
>   }
> };
> ```

``` js
exports.render = function (str, options, locals) {
  for (var partial in options.partials) {
    Handlebars.registerPartial(partial, options.partials[partial]);
  }
  for (var helper in options.helpers) {
    Handlebars.registerHelper(helper, options.helpers[helper]);
  }
  return exports.compile(str, options)(locals);
};
```

See https://github.com/ForbesLindesay/transformers/blob/master/lib/transformers.js#L177-L184

**Comment by hemanth** [comment]
@TimothyGu Thanks, was also looking into fit in hogan to the same design.

**Comment by TimothyGu** [comment]
@hemanth It should be easy enough. The _real_ question is how to fit engines like doT with a third object else than options (compile-time locals).

**Comment by ForbesLindesay** [comment]
Also, the `render` method is redundant here because it matches the behaviour of the jstransformers fallback.

**Comment by hemanth** [comment]
@ForbesLindesay @TimothyGu ^ Sounds OK?

**Comment by ForbesLindesay** [comment]
LGTM

**Comment by ForbesLindesay** [comment]
@hemanth do you want to publish this to npm?

**Comment by hemanth** [comment]
@ForbesLindesay Doing it now.

**Comment by hemanth** [comment]
@ForbesLindesay I'm sticking to the pattern I observed in this org, first version `npm version patch` but I would vote for `npm version major` for a stable release.

**Comment by ForbesLindesay** [comment]
I started out with that while I was figuring out what the API should look like.  Now I'm fairly happy that the jstransformer standard is stable I'm tending to make the first release be 1.0.0 (e.g. https://github.com/jstransformers/jstransformer-underscore).

**Comment by hemanth** [comment]
Cool! :+1:
